---

- name: Ensure Vaultwarden paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ vaultwarden_uid }}"
    group: "{{ vaultwarden_gid }}"
  with_items:
    - "{{ vaultwarden_base_path }}"
    - "{{ vaultwarden_data_dir_path }}"
    - "{{ vaultwarden_cache_dir_path }}"
    - "{{ vaultwarden_ephemeral_dir_path }}"

- name: Ensure Vaultwarden support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ vaultwarden_base_path }}/{{ item }}"
    owner: "{{ vaultwarden_uid }}"
    group: "{{ vaultwarden_gid }}"
    mode: 0640
  with_items:
    - env
    - labels

- name: Ensure Vaultwarden image is pulled
  community.docker.docker_image:
    name: "{{ vaultwarden_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ vaultwarden_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else vaultwarden_container_image_force_pull }}"
  register: result
  retries: 10
  delay: 30
  until: result is not failed

- name: Ensure Vaultwarden container network is created
  community.general.docker_network:
    name: "{{ vaultwarden_container_network }}"
    driver: bridge

- name: Ensure Vaultwarden systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/vaultwarden.service.j2"
    dest: "/etc/systemd/system/{{ vaultwarden_identifier }}.service"
    mode: 0640