---

- block:
    - name: Validate vaultwarden config
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Vaultwaden
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  when: "'uninstall' not in ansible_run_tags"
  tags: always

- block:
    - when: Uninstall Vaultwarden
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - uninstall