---
- name: Fail if required Vaultwarden settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - vaultwarden_hostname

- name: Fail if using unsupported database type
  ansible.builtin.fail:
    msg: >-
      Unsupported database type: `{{ vaultwarden_database_type }}`
  when:
    - "not vaultwarden_database_type == 'postgres'"
    - "not vaultwarden_database_type == 'sqlite'"

- name: Fail if required Vaultwarden + Postgres integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `vaultwarden_database_type` is `postgres`
  when: "vaultwarden_database_type == 'postgres' and vars[item] == ''"
  with_items:
    - vaultwarden_database_username
    - vaultwarden_database_password
    - vaultwarden_database_hostname
