---
name: Integration
on:
  push:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # first of each month
    - cron: '0 0 1 * *'

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2.4.0

      - name: Set up Python 3.
        uses: actions/setup-python@v2.3.2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible-lint molecule yamllint requests

      - name: Install community.docker
        run: ansible-galaxy collection install community.docker community.general

      - name: Install role dependencies.
        run: ansible-galaxy install geerlingguy.docker geerlingguy.pip

      - name: Run Molecule tests.
        run: molecule test -s default
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
